[package]
name = "bitfields"
version = "1.0.0"
authors = ["Daniel Lehmann <danlehmannmuc@gmail.com>"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = "1.0"
quote = "1.0"
proc-macro2 = "1.0"
arbitrary-int = "1.0.0"