//! Compile-time checks for the code generated by the `bitbybit`/`bitenum` proc macros.
//!
//! `clippy::must_use_candidate` only lints items that are truly public, and items inside an
//! integration-test binary are never considered public by the lint (`is_exported` is false for the
//! test harness). To give the `#[must_use]` annotations on the generated methods real enforcement,
//! the check therefore has to live in a library crate and be linted explicitly by CI:
//!
//! ```text
//! cargo clippy -p bitbybit-compile-checks
//! ```
//!
//! The bitfield below deliberately exercises every kind of generated accessor: plain and indexed
//! getters and setters, read-only / write-only / read-write fields, arbitrary-int fields and the
//! introspection `mask_*`/`*_BITS` helpers. If any future change to the macro drops a `#[must_use]`
//! from one of these generated methods, this crate fails to compile.

#![deny(clippy::must_use_candidate)]

#[allow(unused_imports)] // used by the macros below, re-emitted into generated code
use arbitrary_int::{u1, u3, u4};
use bitbybit::{bitenum, bitfield};

/// Bitfield covering every generated method shape.
#[bitfield(u32, default = 0)]
pub struct Everything {
    /// Read-write bool field (non-array getter + setter + builder entry).
    #[bit(0, rw)]
    pub flag: bool,
    /// Read-write arbitrary-int field (non-array indexed-codegen path).
    #[bits(1..=3, rw)]
    pub small: u3,
    /// Array field (indexed getter/setter + builder array expansion).
    #[bit(4, rw, stride = 1)]
    pub row: [u1; 4],
    /// Read-only field (getter only).
    #[bit(8, r)]
    pub read_only: bool,
    /// Write-only field (setter + builder entry only, no getter).
    #[bit(9, w)]
    pub write_only: bool,
    /// Custom bitenum field (custom-type getter/setter conversion).
    #[bits(10..=11, rw)]
    pub color: Color,
}

/// The custom type used by [`Everything::color`].
#[bitenum(u2, exhaustive = true)]
pub enum Color {
    Red = 0,
    Green = 1,
    Blue = 2,
    Cyan = 3,
}
