name: test release
run-name: ${{ github.actor }}'s patch
on: [push, pull_request]
jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: with-defmt
            args: '--release --no-default-features --features defmt'
          - name: without-defmt
            args: '--release --no-default-features'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: ${{ matrix.args }}

  build-no-std:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: "thumbv7em-none-eabihf"
      # I'd prefer --manifest-path ./qemu-tests/Cargo.toml, but I think this ignores
      # the .cargo/config.toml file inside the QEMU test folder.
      - run: cd qemu-tests && cargo build --target thumbv7em-none-eabihf --release
